#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ">>>>>>>> Husky Pre-commit: Fixing lint"
echo ""
npm run lint:fix

echo ">>>>>>>> Husky Pre-commit: Transpiling sources"
echo ""
npm run transpile
# dist/ is gitignored - not staged here
